##MySql
spring:
  datasource:
    url: jdbc:mysql://x.x.x.x:3306/x?serverTimezone=Asia/Seoul
    username: x
    password: x
  jpa:
    database: default
    hibernate:
      ddl-auto: update
    generate-ddl: true
    show-sql: true

##SQL Server
sqlserver:
  datasource:
    url: jdbc:mysql://x.x.x.x:3306/x?serverTimezone=Asia/Seoul
    username: x
    password: x
